version: '3'
services:
  mongo:
    image: 'mongo:latest'
    container_name: mongodb
    ports:
      - 27016:27017
    volumes:
      - mongodb:/data/db
    networks:
      - tweet-app
  backend:
    build: ./backend/tweet-app
    container_name: tweet-app-backend
    ports:
      - 9099:8099
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=tweet_app
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - CORS_ALLOWED_ORIGINS=http://localhost:3001
    networks:
      - tweet-app
    depends_on:
      - mongo
      - kafka
  frontend:
    build:
      context: ./frontend/tweet-app
      args:
        - REACT_APP_BACKEND_BASE_URL=http://localhost:9099/api/v1.0/tweets/
        - REACT_APP_WS_CONNECT_URL=http://localhost:9099/ws/live-tweets-ws
        - REACT_APP_WS_TWEETS_SUB_EP=/ws/tweets
    container_name: tweet-app-frontend
    ports:
      - 3001:80
    networks:
      - tweet-app
    volumes:
      - nginx:/etc/nginx/conf.d
    depends_on:
      - backend

  #Zookeeper and Kafka
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - 2182:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - tweet-app
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - 9093:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - kafka:/usr/share/kafka/data
    networks:
      - tweet-app
    depends_on:
      - zookeeper

  # ELK Stack
  elasticsearch:
    image: 'elasticsearch:7.12.0'
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9201:9200
    volumes:
      - elk:/usr/share/elasticsearch/data
    networks:
      - tweet-app
  logstash:
    build: ./backend/logstash
    container_name: logstash
    ports:
      - 5045:5044
      - 9601:9600
    environment:
      - ELASTIC_SEARCH_HOST=elasticsearch
      - ELASTIC_SEARCH_PORT=9200
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_TOPIC=tweet-app-logs
      - PATH_CONFIG=/usr/share/logstash/pipeline/logstash.conf
      - CONFIG_DEBUG=true
      - LOG_LEVEL=debug
    volumes:
      - elk:/usr/share/logstash/data
    networks:
      - tweet-app
    depends_on:
      - elasticsearch
      - kafka
  kibana:
    image: 'kibana:7.12.0'
    container_name: kibana
    ports:
      - 5602:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - elk:/usr/share/kibana/data
    networks:
      - tweet-app
    depends_on:
      - elasticsearch

networks:
  tweet-app: {}
volumes:
  mongodb:
  elk:
  kafka:
  nginx:
