server:
  port: 8099
spring:
  application:
    name: tweet-app
  data:
    mongodb:
      database: ${MONGO_DB}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
      # authentication-database: admin
      # username: root
      # password: root
      auto-index-creation: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
kafka:
  bootstrap-address: ${KAFKA_HOST}:${KAFKA_PORT}
cors:
  allowed-origins: http://localhost:3000
