server:
  port: 8099
spring:
  application:
    name: tweet-app
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
management:
  endpoints:
    web:
      exposure:
        include: '*'
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
